# Generated by Django 5.1.3 on 2024-11-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user_pwd_token',
            new_name='token',
        ),
    ]
