# Generated by Django 5.1.3 on 2024-11-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_token_useraccount_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_token',
            field=models.CharField(blank=True, default='w0tgaDTwqRa6BIVtzz8tHyesh', max_length=300),
        ),
    ]
