# Generated by Django 5.1.3 on 2024-11-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_useraccount_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_token',
            field=models.CharField(blank=True, default='wNIfq1s1Kleobo4pua1XtfZsi', max_length=300),
        ),
    ]
