# Generated by Django 5.1.3 on 2024-11-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_useraccount_user_token'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='program',
            field=models.ManyToManyField(to='leads.program'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_token',
            field=models.CharField(blank=True, default='jdiybmXVfBlUs40Savog73dDW', max_length=300),
        ),
    ]
