# Generated by Django 5.1.3 on 2024-11-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_useraccount_program_alter_useraccount_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_token',
            field=models.CharField(blank=True, default='jgZfGnRG33AFzVUX4MZ0ZcxaC', max_length=300),
        ),
    ]
