# Generated by Django 5.1.3 on 2024-11-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_useraccount_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_token',
            field=models.CharField(blank=True, default='YShOPJ80pS6IJ28dUVxVdB6dC', max_length=300),
        ),
    ]
