# Generated by Django 5.1.3 on 2024-11-14 06:37

import django.db.models.deletion
import leads.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dropdown', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercials', models.CharField(max_length=100)),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(blank=True, default='', max_length=100)),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RemarkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(blank=True, default='', max_length=100)),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TurnArroundTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommercialApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial', models.CharField(max_length=100)),
                ('approval_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.approvaltype')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.approvalstatus')),
            ],
        ),
        migrations.CreateModel(
            name='FollowupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='0001/01/01')),
                ('time', models.TimeField()),
                ('notes', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('field', models.JSONField(blank=True, decoder=leads.models.JsonDecoder, default=list, encoder=leads.models.JsonEncoder, null=True)),
                ('previous', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('new', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.actiontype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot_lead', models.BooleanField(default=False)),
                ('client_id', models.CharField(blank=True, default='', max_length=100)),
                ('request_id', models.CharField(blank=True, default='', max_length=100)),
                ('provider_id', models.CharField(blank=True, default='', max_length=100)),
                ('requester_id', models.CharField(blank=True, default='', max_length=100)),
                ('requester_location', models.CharField(blank=True, default='', max_length=100)),
                ('requester_sell_in_country', models.CharField(blank=True, default='', max_length=100)),
                ('service_requester_type', models.CharField(blank=True, default='', max_length=100)),
                ('marketplace', models.CharField(blank=True, default='', max_length=100)),
                ('current_status', models.CharField(blank=True, default='', max_length=100)),
                ('client_name', models.CharField(blank=True, default='', max_length=100)),
                ('contact_number', models.CharField(blank=True, default='', max_length=100)),
                ('alternate_contact_number', models.CharField(blank=True, default='', max_length=100)),
                ('email_id', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('alternate_email_id', models.EmailField(blank=True, default='', max_length=254)),
                ('business_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('brand_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('gst', models.CharField(blank=True, default='', max_length=100)),
                ('seller_address', models.CharField(blank=True, default='', max_length=500)),
                ('seller_website', models.CharField(blank=True, default='', max_length=100)),
                ('amazon_store_link', models.CharField(blank=True, default='', max_length=100)),
                ('facebook_store_link', models.CharField(blank=True, default='', max_length=100)),
                ('instagram_store_link', models.CharField(blank=True, default='', max_length=100)),
                ('created_date', models.CharField(blank=True, default='', max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('visibility', models.BooleanField(default=True)),
                ('business_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.businesscategory')),
                ('business_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.businesstype')),
                ('client_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.clientdesignation')),
                ('client_turnover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.clientturnover')),
                ('contact_preferences', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.contactpreference')),
                ('firm_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.firmtype')),
                ('history', models.ManyToManyField(to='leads.leadhistory')),
                ('lead_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('remark', models.ManyToManyField(to='leads.remarkhistory')),
            ],
        ),
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('date', models.DateField()),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead_id', models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, default='', max_length=100)),
                ('mou_required', models.BooleanField(default=True, null=True)),
                ('comments', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('service_validity', models.IntegerField(null=True)),
                ('visibility', models.BooleanField(default=True)),
                ('commercials', models.ManyToManyField(to='leads.commercials')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.marketplace')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.paidby')),
                ('payment_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.paymentmodel')),
                ('payment_terms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.paymentterms')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.program')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, default='', max_length=100)),
                ('visibility', models.BooleanField(default=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.segment')),
            ],
        ),
        migrations.AddField(
            model_name='marketplace',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.service'),
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(blank=True, default='', max_length=100)),
                ('mou', models.FileField(blank=True, default='', null=True, upload_to='mou')),
                ('payment_proof', models.FileField(blank=True, default='', null=True, upload_to='paymentproof')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('subscription_start_date', models.DateTimeField(auto_now=True, null=True)),
                ('subscription_end_date', models.DateTimeField(auto_now=True, null=True)),
                ('associate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commecials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.commercials')),
                ('commercial_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.commercialapproval')),
                ('followup', models.ManyToManyField(to='leads.followuphistory')),
                ('history', models.ManyToManyField(to='leads.leadhistory')),
                ('not_interested_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.notinterested')),
                ('payment_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.approvalstatus')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.program')),
                ('remark', models.ManyToManyField(to='leads.remarkhistory')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.leadstatus')),
                ('unresponsive_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.unresponsive')),
            ],
        ),
        migrations.AddField(
            model_name='remarkhistory',
            name='lead_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.servicecategory'),
        ),
        migrations.AddField(
            model_name='leads',
            name='service_category',
            field=models.ManyToManyField(to='leads.servicecategory'),
        ),
        migrations.AddField(
            model_name='commercials',
            name='lead_id',
            field=models.ManyToManyField(to='leads.servicecategory'),
        ),
        migrations.AddField(
            model_name='commercialapproval',
            name='service_category_all',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_category_of', to='leads.servicecategory'),
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateTimeField(auto_now=True)),
                ('service_category_all', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.servicecategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdown.leadstatus')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='status_history',
            field=models.ManyToManyField(to='leads.statushistory'),
        ),
    ]
