# Generated by Django 5.1.3 on 2024-11-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialapproval',
            old_name='service_category_all',
            new_name='service_category',
        ),
        migrations.RenameField(
            model_name='statushistory',
            old_name='service_category_all',
            new_name='service_category',
        ),
    ]
