# Generated by Django 5.1.3 on 2024-11-15 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_rename_service_category_all_commercialapproval_service_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='commecials',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='commercials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercials_of', to='leads.commercials'),
        ),
        migrations.AlterField(
            model_name='commercials',
            name='lead_id',
            field=models.ManyToManyField(related_name='lead_id_of', to='leads.servicecategory'),
        ),
    ]
