# Generated by Django 5.1.3 on 2024-11-15 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country_Code',
            new_name='CountryCode',
        ),
    ]
